apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-core-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:moabukar/gitops-argo.git
    path: registry/argo-core/components/argo-core
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
